attach_path: F:/chinasoft/code/ProjectManageSystem/hyp/attach/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 19931229
    druid:
      initialSize: 10 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      maxActive: 200 #最大连接池数量
      minIdle: 10 #最小连接池数量
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      maxOpenPreparedStatements: 100 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      validationQuery: SELECT 1 #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      timeBetweenEvictionRunsMillis: 180000 #有两个含义： 1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      minEvictableIdleTimeMillis: 180000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      connectionProperties: 100
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
    messages:
      encoding: UTF-8

  #  文件大小 MB必须大写
  #  maxFileSize 是单个文件大小
  #  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      file-size-threshold: 2KB
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
#--------------------------server设置---------------------------
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8



